### ISSUE TITLE
의약품 검색 페이지 UI

### ISSUE THREAD

**Issue by yujiah-github** [ITCompetition-Mediger/Mediger-frontend#10]
- [x] 의약품 검색 페이지 UI 작업

**Comment by yujiah-github** [comment]
- [x] 의약품 검색 성공 페이지 추가
- [ ] 의약품 검색 실패 페이지 추가
- [x] 의약품 검색 시, 세부 페이지 추가
- [ ] 의약품 스크랩 시, 페이지 추가
